# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in html_mailer.gemspec
gemspec

gem "rake", "~> 13.0"

spec.files = Dir["lib/**/*.rb", "LICENSE", "README.md"]
