name: Pull Code on Main Push
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pull_code:
    name: Pull Code
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Clone repository using SSH
        run: git clone git@github.com:pmickeyc/CloudApplicationDevelopment.git
        env:
          GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

      - name: Cleanup SSH
        run: rm -rf ~/.ssh/
        env:
          GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

      - name: Cleanup SSH
        run: rm -rf ~/.ssh/
