name: Clone and Operate on Repository
on:
  push:
    branches:
      - main

jobs:
  clone_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH for GitHub
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Clone Repository using SSH
        run: |
          GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"
          # Add additional Git commands here if needed

      - name: Cleanup SSH
        run: rm -rf ~/.ssh/
