name: Pull Code on Main Push
on:
  push:
    branches:
      - main  # Replace 'main' with your branch name or add more branches as needed
  workflow_dispatch:

jobs:
  pull_code:
    name: Pull Code
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH for GitHub
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Stop Rails Server
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "pkill -f 'rails s'"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: SSH into Linux Server and Pull Code
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}/CloudApplicationDevelopment && git pull && rails asset:precompile && rails s"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Cleanup SSH
        run: rm -rf ~/.ssh/
